### ISSUE TITLE
After receiving JTW token, refuses to authorize subsequent requests

### ISSUE THREAD

**Issue by antonskv** [docusign/eg-01-php-jwt#6]
Hi, 

I'm using your examples, trying to make sense of it. I'm getting JWT token back from the DS server, but any attempt to use it ends up with 401/Unauthorized. I'm kind of stuck with nowhere else to go from here. This is for server-side integration using JWT flow. 

I took me a while to figure out proper token encoding and to use integration key ID for iss and sub, but i finally got a response with a token. 

Returned JWT token gets set as a class property and then i'm trying to call getUserInfo function that contains following: 

``
$this->output->writeln("[".date("Y-m-d H:i:s")."] Trying to get user info...");  
        
        $user_info_url="https://{$this->authServer}/oauth/userinfo";
        $headers = array('Accept' => 'application/json', 'Authorization' => "Bearer {$this->jwtToken}");
        $response = \Unirest\Request::get($user_info_url, $headers);

        $json = $response->body;
        
        print_r($response);
``
Token has to be valid, because i'm getting it from the DS server. Yet it does not allow me to talk to the server.

``
[2020-02-05 15:02:39] Running imn:cb:docusign command in dev
[2020-02-05 15:02:39] No token found!
[2020-02-05 15:02:39] Encoded JWT: eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpc3MiOiIxNDE1NmFlYi05MTI1LTQ5ZTgtYTE3OC00ZTQ0OTAwNjJkNzQiLCJzdWIiOiIxNDE1NmFlYi05MTI1LTQ5ZTgtYTE3OC00ZTQ0OTAwNjJkNzQiLCJhdWQiOiJhY2NvdW50LWQuZG9jdXNpZ24uY29tIiwic2NvcGUiOiJzaWduYXR1cmUgaW1wZXJzb25hdGlvbiIsIm5iZiI6MTU4MDkzMjk1OSwiZXhwIjoxNTgwOTkyOTU5fQ.S9K-ro48KzVz4xxJfIb9-MadAMVARfeqMzA_IXbE7cIg_ktMlpBX4b3S5YlqJTmf2TQiXt2uJcuMAgO9zWYjP7jEQGUQd0IT9VbMXhW7MrDVW3WGEIabdKCDg7L13ccp2B22TcX96hPy6TugwMXWI15HFvWH5Y3hC-wc6_wo8xnuCtqPCGkndWqUzdwwfjPICc4Shcv5n8C16HpvvOomfYkYWtXyP4Rxqh551kAB5-76aYCWxPtZad_S3NGfox9ptOc5cLplbOdulmt5Qm4WycU3wixOLhvsufRWODKifDjPTwA216go2Lfn7f8QAIIaO4ba_eYReciE7l-IcygBew
[2020-02-05 15:02:39] Requesting access token....
stdClass Object
(
    [access_token] => eyJ0eXAiOiJNVCIsImFsZyI6IlJTMjU2Iiwia2lkIjoiNjgxODVmZjEtNGU1MS00Y2U5LWFmMWMtNjg5ODEyMjAzMzE3In0.AQkAAAABAAsADQAkAAAAMTQxNTZhZWItOTEyNS00OWU4LWExNzgtNGU0NDkwMDYyZDc0IgAkAAAAMTQxNTZhZWItOTEyNS00OWU4LWExNzgtNGU0NDkwMDYyZDc0BwCA2Q5adqrXSAgAgBkyaLmq10gLAB8AAABodHRwczovL2FjY291bnQtZC5kb2N1c2lnbi5jb20vDAAkAAAAMTQxNTZhZWItOTEyNS00OWU4LWExNzgtNGU0NDkwMDYyZDc0GAACAAAABQAAAB0AAAASAAEAAAAGAAAAand0X2Jy.m1xCFBFyuhKNcqJW-wUZjrnNWqgzUJcVsfYnb_cQ0YO-Qjv-HelEA6CdJ1pDgnIAZk1hgYkYuelfqten1acmChqhFdFIs5sW1K058gXBCpJZftIrGWdWNGiEUi5jQFiEhSO0s-CMud2b2GocRyODo-Z85HE22ByLw9hOlBWTqcEWMqNK--buALgBDh1PcvFF9oZPkPtZMQbVczMEtQlRN9rllZfc8XPuYaC2Xe7ZrCYbyef-w7YxXyaS_D_qCxR6HZOfq7U6ig7qGVhjUl_DM7PaObgZrTr46DgtZAlmeHSjq3lhJRiNiR1uIUDWbkID3_2r0-hoXpIuLNSWzuvD1w
    [token_type] => Application
    [expires_in] => 28800
)
[2020-02-05 15:02:39] Received token: eyJ0eXAiOiJNVCIsImFsZyI6IlJTMjU2Iiwia2lkIjoiNjgxODVmZjEtNGU1MS00Y2U5LWFmMWMtNjg5ODEyMjAzMzE3In0.AQkAAAABAAsADQAkAAAAMTQxNTZhZWItOTEyNS00OWU4LWExNzgtNGU0NDkwMDYyZDc0IgAkAAAAMTQxNTZhZWItOTEyNS00OWU4LWExNzgtNGU0NDkwMDYyZDc0BwCA2Q5adqrXSAgAgBkyaLmq10gLAB8AAABodHRwczovL2FjY291bnQtZC5kb2N1c2lnbi5jb20vDAAkAAAAMTQxNTZhZWItOTEyNS00OWU4LWExNzgtNGU0NDkwMDYyZDc0GAACAAAABQAAAB0AAAASAAEAAAAGAAAAand0X2Jy.m1xCFBFyuhKNcqJW-wUZjrnNWqgzUJcVsfYnb_cQ0YO-Qjv-HelEA6CdJ1pDgnIAZk1hgYkYuelfqten1acmChqhFdFIs5sW1K058gXBCpJZftIrGWdWNGiEUi5jQFiEhSO0s-CMud2b2GocRyODo-Z85HE22ByLw9hOlBWTqcEWMqNK--buALgBDh1PcvFF9oZPkPtZMQbVczMEtQlRN9rllZfc8XPuYaC2Xe7ZrCYbyef-w7YxXyaS_D_qCxR6HZOfq7U6ig7qGVhjUl_DM7PaObgZrTr46DgtZAlmeHSjq3lhJRiNiR1uIUDWbkID3_2r0-hoXpIuLNSWzuvD1w
[2020-02-05 15:02:39] Trying to get user info...
Unirest\Response Object
(
    [code] => 401
    [raw_body] => {"error":"internal_server_error","reference_id":"a5428bc4-2f04-4b28-a7cc-e6d2b9d38fdc"}
    [body] => stdClass Object
        (
            [error] => internal_server_error
            [reference_id] => a5428bc4-2f04-4b28-a7cc-e6d2b9d38fdc
        )

    [headers] => Array
        (
            [0] => HTTP/1.1 401 Unauthorized
            [Cache-Control] => no-cache
            [Pragma] => no-cache
            [Content-Type] => application/json; charset=utf-8
            [Expires] => -1
            [X-DocuSign-TraceToken] => a5428bc4-2f04-4b28-a7cc-e6d2b9d38fdc
            [X-DocuSign-Node] => SE2DFE2
            [Date] => Wed, 05 Feb 2020 20:02:39 GMT
            [Content-Length] => 87
            [Vary] => Accept-Encoding
        )

)

``

**Comment by antonskv** [comment]
So to make it simpler, if i clone your repo, configure my values into ds_config.ini, this is the output i'm getting there as well. My client_id is my integration key ID and impersonated user is the same value (otherwise i keeps asking for user consent).

``
ubuntu@ip-10-200-0-13:~/eg-01-php-jwt$ php -f main.php 

Sending an envelope...
Requesting an access token via the JWT flow...done. Continuing...PHP Notice:  Undefined property: stdClass::$accounts in /home/ubuntu/eg-01-php-jwt/lib/example_base.php on line 108
PHP Warning:  Invalid argument supplied for foreach() in /home/ubuntu/eg-01-php-jwt/lib/example_base.php on line 111
PHP Notice:  Undefined variable: account in /home/ubuntu/eg-01-php-jwt/lib/example_base.php on line 119
PHP Warning:  Invalid argument supplied for foreach() in /home/ubuntu/eg-01-php-jwt/lib/example_base.php on line 119


Exception!


User does not have access to account 


Done.
``

**Comment by LarryKlugerDS** [comment]
Sorry you're having this trouble. The `impersonated user guid` is NOT the same as the integration key (also known as the client id).

Look up the user guid via the admin tool. -- Use the Users tab. 

I just cloned this repo, configured it, and it worked fine. 

You can use stackoverflow with tag `docusignapi` for this type of use question.

Regards,
Larry

**Comment by antonskv** [comment]
Larry, 

I tried that, but if i specify impersonated user ID, then it requires web based consent. Which means i can't do server only integration. Our integration is server-to-server, we can't require web based consent for every user.

Sincerely,

Anton

**Comment by LarryKlugerDS** [comment]
Consent is a one time operation per impersonated person. Your app can send the URL via email for the person to execute on their browser.

Or use administrative consent to proactively consent on behalf of everyone in your account. See the consent page on Developer center

**Comment by antonskv** [comment]
OK, i think i got that logic, but i don't see an ability to add organizational admins, neither in sandbox or our main account. 

So page i ended up finding: 
https://developers.docusign.com/esign-rest-api/guides/authentication/obtaining-consent#admin-consent-for-internal-applications

That led me to this one:
https://support.docusign.com/en/guides/org-admin-guide-org-admins

Anyway, this is something not related to API, so i'll just bug our sales rep about it. Thanks for your help and quick reply. Really appreciate it!

**Comment by LarryKlugerDS** [comment]
You can have organization admin enabled for your developer account by contacting go-live@docusign.com

**Comment by antonskv** [comment]
And to get accountID for users when organization account is enabled, the "sub" part inside the JWT token needs to point to organization admin?

**Comment by LarryKlugerDS** [comment]
No, the jwt Grant process is the whether you have org admin or not. To obtain the user's account Id(s) and other information, use the userinfo oauth API -- https://developers.docusign.com/esign-rest-api/guides/authentication/user-info-endpoints
